global using Autofac.Extensions.DependencyInjection;
global using Autofac;
global using FluentValidation;
global using MediatR;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Diagnostics.HealthChecks;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc.Authorization;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Server.Kestrel.Core;
global using Microsoft.AspNetCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore;
global using System.Collections.Generic;
global using System.Data.Common;
global using System.Data.SqlClient;
global using System.IdentityModel.Tokens.Jwt;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Reflection;
global using System.Runtime.Serialization;
global using System.Threading.Tasks;
global using System.Threading;
global using System;
global using UserId = System.Guid;
global using CommandAsk = Inklio.Api.Application.Commands.Ask;
global using CommandTag = Inklio.Api.Application.Commands.Tag;
global using DomainAsk = Inklio.Api.Domain.Ask;
global using DomainAskImage = Inklio.Api.Domain.AskImage;
global using DomainDelivery = Inklio.Api.Domain.Delivery;
global using DomainDeliveryImage = Inklio.Api.Domain.DeliveryImage;
global using DomainTag = Inklio.Api.Domain.Tag;
