# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    - dev
  paths:
    include:
      - 'Services/Inklio.Sql'

pool:
  vmImage: ubuntu-latest

steps:

## Build and Deploy SQL changes
- script: |
    dotnet tool install -g microsoft.sqlpackage
  displayName: "dotnet tool install -g microsoft.sqlpackage"

- script: |
    cd ./Services/Inklio.Sql
    dotnet build ./Inklio.Sql.sqlproj /p:NetCoreBuild=true
  displayName: "dotnet build ./Inklio.Sql.sqlproj /p:NetCoreBuild=true"

- script: |
    cd ./Services/Inklio.Sql
    sqlpackage /Action:Publish /SourceFile:"./bin/Release/Inklio.Sql.dacpac" /TargetConnectionString:"$(sqlConnectionString)"
  displayName: "sqlpackage publish"

- script: |
    echo "Saving git commit short hash into gitshorthash variable:"
    gitshorthash=$(git rev-parse --short HEAD)
    echo $gitshorthash
    echo "##vso[task.setvariable variable=gitshorthash;]$gitshorthash"
  displayName: Save Git Short Hash


