trigger:
- dev

variables:
- name: configuration
  value: Release
- group: inklio-vars

## Build API application
steps:
- script: |
    echo "Saving git commit short hash into gitshorthash variable:"
    gitshorthash=$(git rev-parse --short HEAD)
    echo $gitshorthash
    echo "##vso[task.setvariable variable=gitshorthash;]$gitshorthash"
  displayName: Save Git Short Hash

- task: UseDotNet@2
  displayName: Use .Net 6.0.x
  inputs:
    version: '6.0.x'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    configuration: $(configuration)
    arguments: /p:InformationalVersion="1.0.0.$(gitshorthash)"
    projects: |
      **/*.csproj
      !**/*.sqlproj
      
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    configuration: $(configuration)
    projects: |
      **/*Tests.csproj
      **/*Test.csproj
      !**/*.sqlproj
    arguments: '--nologo'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish Inklio.Api'
  inputs:
    command: publish
    configuration: $(configuration)
    projects: |
      **/Inklio.Api.csproj
    arguments: /p:InformationalVersion="1.0.0.$(gitshorthash)"
    publishWebProjects: false


## Build Web application
- task: UseNode@1
  inputs:
    version: '18'
  displayName: 'Use Node.js'

- script: |
    # Install Yarn package manager
    npm install -g yarn
  displayName: 'npm install -g yarn'

- script: |
    # Install project dependencies
    cd ./Client/Web/inklio
    yarn install
  displayName: 'yarn install'

- script: |
    # Build the web application
    cd ./Client/Web/inklio
    yarn run build
  displayName: 'yarn run build'


## Docker Build and Publish applications

- task: Docker@2
  displayName: Docker Inklio.Web
  inputs:
    DockerFile: Client/Web/inklio/Dockerfile
    containerRegistry: inklio.azurecr.io
    repository: 'docker/inklio.web'
    command: buildAndPush
    tags: |
      $(Build.SourceVersion)
      latest

- task: Docker@2
  displayName: Docker Inklio.Api
  inputs:
    DockerFile: Services/Inklio.Api/Dockerfile
    containerRegistry: inklio.azurecr.io
    repository: 'docker/inklio.api'
    command: buildAndPush
    tags: |
      $(Build.SourceVersion)
      latest

- task: Docker@2
  displayName: Docker Reverse Proxy
  inputs:
    DockerFile: ReverseProxy/Dockerfile
    containerRegistry: inklio.azurecr.io
    repository: 'docker/reverseproxy'
    command: buildAndPush
    tags: |
      $(Build.SourceVersion)
      latest
