trigger:
- dev

variables:
- name: configuration
  value: Release
- group: InklioSql

steps:
- task: UseDotNet@2
  displayName: Use .Net 6.0.x
  inputs:
    version: '6.0.x'

- script: |
    echo "Saving git commit short hash into gitshorthash variable:"
    gitshorthash=$(git rev-parse --short HEAD)
    echo $gitshorthash
    echo "##vso[task.setvariable variable=gitshorthash;]$gitshorthash"
  displayName: Save Git Short Hash

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    configuration: $(configuration)
    arguments: /p:InformationalVersion="1.0.0.$(gitshorthash)"
    projects: |
      **/*.csproj
      !**/*.sqlproj
      
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    configuration: $(configuration)
    projects: |
      **/*Tests.csproj
      **/*Test.csproj
      !**/*.sqlproj
    arguments: '--nologo'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    configuration: $(configuration)
    projects: |
      **/Inklio.Api.csproj
    arguments: /p:InformationalVersion="1.0.0.$(gitshorthash)"
    publishWebProjects: false

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    configuration: $(configuration)
    projects: |
      **/Inklio.Auth.csproj
    arguments: /p:InformationalVersion="1.0.0.$(gitshorthash)"
    publishWebProjects: false

- task: Docker@2
  displayName: Docker build and Inklio.Web
  inputs:
    DockerFile: Web/inklio/Dockerfile
    containerRegistry: inklio.azurecr.io
    repository: 'docker/inklio.web'
    command: buildAndPush
    tags: |
      $(Build.SourceVersion)
      latest

- task: Docker@2
  displayName: Docker build and push Inklio.Api
  inputs:
    DockerFile: Services/Inklio.Api/Dockerfile
    containerRegistry: inklio.azurecr.io
    repository: 'docker/inklio.api'
    command: buildAndPush
    tags: |
      $(Build.SourceVersion)
      latest

- task: Docker@2
  displayName: Docker build and push Inklio.Auth
  inputs:
    DockerFile: Services/Inklio.Auth/Dockerfile
    containerRegistry: inklio.azurecr.io
    repository: 'docker/inklio.auth'
    command: buildAndPush
    tags: |
      $(Build.SourceVersion)
      latest

- task: Docker@2
  displayName: Docker build and push Reverse Proxy
  inputs:
    DockerFile: ReverseProxy/Dockerfile
    containerRegistry: inklio.azurecr.io
    repository: 'docker/reverseproxy'
    command: buildAndPush
    tags: |
      $(Build.SourceVersion)
      latest