CREATE TABLE [dbo].[Comment]
(
  [Id] INT NOT NULL PRIMARY KEY,
  [AskId] INT FOREIGN KEY REFERENCES Ask(Id) DEFAULT NULL,
  [Body] NVARCHAR NOT NULL,
  [CanComment] BIT DEFAULT 1,
  [CanEdit] BIT DEFAULT 1,
  [CanFlag] BIT DEFAULT 1,
  [CreatedAtUtc] DATETIME2 NOT NULL,
  [CreatedById] NVARCHAR(32) NOT NULL,
  [CommentTypeId] TINYINT,
  [DeliveryId] INT FOREIGN KEY REFERENCES DeliveryId(Id) DEFAULT NULL,
  [EditedAtUtc] DATETIME2 NULL,
  [EditedById] NVARCHAR(32) NULL,
  [FlagCount] INT DEFAULT 0,
  [IsDeleted] BIT DEFAULT 0,
  [IsLocked] BIT DEFAULT 0,
  [LockedAtUtc] DATETIME2 NULL,
  [SaveCount] INT DEFAULT 0,
  [ThreadId] INT FOREIGN KEY REFERENCES Ask(Id),
  [UpvoteCount] INT DEFAULT 0,
  [ViewCount] int DEFAULT 0,
)
