CREATE TABLE [dbo].[Delivery]
(
  [id] INT NOT NULL PRIMARY KEY,
  [askId] INT FOREIGN KEY REFERENCES Ask(id),
  [body] NVARCHAR NOT NULL,
  [canComment] BIT DEFAULT 1,
  [canDeliver] BIT DEFAULT 1,
  [canEdit] BIT DEFAULT 1,
  [canFlag] BIT DEFAULT 1,
  [canTag] BIT DEFAULT 1,
  [createdAtUtc] DATETIME2 NOT NULL,
  [createdBy] NVARCHAR(32) NOT NULL,
  [editedAtUtc] DATETIME2 NULL,
  [editedBy] NVARCHAR(32) NULL,
  [flagCount] INT DEFAULT 0,
  [isDeleted] BIT DEFAULT 0,
  [isLocked] BIT DEFAULT 0,
  [isNsfw] BIT DEFAULT 0,
  [isNsfl] BIT DEFAULT 0,
  [lockedAtUtc] DATETIME2 NULL,
  [saveCount] INT DEFAULT 0,
  [title] NVARCHAR(256) NOT NULL,
  [upvoteCount] INT DEFAULT 0,
  [viewCount] int DEFAULT 0,
)
