CREATE TABLE [auth].[DataProtectionKeys]
(
	[Id] INT IDENTITY(1,1) NOT NULL,
	[FriendlyName] [nvarchar](MAX) NULL,
	[Xml] [nvarchar](MAX) NULL,
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [auth].[DataProtectionKeys] ADD  CONSTRAINT [PK_DataProtectionKeys] PRIMARY KEY CLUSTERED
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO