using Inklio.Api.Client;

public static class SampleDeliveries
{
    public static string[] DeliveryBodies = new string[]
    {
        "Request delivered!",
        "Voila, done.",
        "Ready for you.",
        "done",
        "Here's what was asked for.",
        "As was requested.",
        "Ask delivered!",
        "good to go",
        "I completed the ask.",
        "My contribution.",
        "one delivery",
        "task complete",
        "heer it is as asked",
        "finished",
        "my delivery",
        "done and delivered",
        "Ask complete",
        "delivery!",
        "Enjoy!",
        "Delivered",
        "All done",
        "Finished!",
        "Done.",
        "here you go",
        "It's finished!",
        "delivery",
        "fulfilled",
        "bam!",
        "!!",
        "here",
        "Done!!",
        "finally finished",
        "Fulfilling the Ask.",
        "done as asked",
        "My take on the ask.",
        "Done and done!",
        "completed",
        "One delivery.",
        "As asked!",
        "hope you enjoy",
        "I finished",
        "Got it done.",
        "delivered",
        ".",
        "done",
        "Here's a thing.",
        "as requested",
        "here it is",
        "delivered to you.",
        "DONE",
        "one delivery here",
        "as asked",
        "Here you go",
        "As envisioned",
        "Done!",
        "Completed",
        "Took longer than I thought",
        "Delivered!",
        "Hope you enjoy.",
        "Fulfilling your request.",
        "Completed",
        "All done.",
        "Hope you enjoy.",
        "Here's the delivery.",
        "As requested.",
        "I finished!",
        "Delivery!",
        "Here it is.",
    };

    public static IEnumerable<DeliveryCreate> DeliveryCreates => DeliveryBodies
        .Select(b => new DeliveryCreate() { Body = b })
        .ToArray();
}