using Inklio.Api.Client;

public static class SampleAsks
{
    public static string[] AskBodies = new string[]
    {
        "Could you please create a tranquil sunset over a serene countryside landscape?",
        "I'd love to see your illustration of a futuristic cityscape bustling with flying cars and neon lights.",
        "Would you mind drawing a magical forest where trees have faces and come to life at night?",
        "Imagine an alien planet with bizarre, otherworldly flora and fauna. Could you bring it to life?",
        "Capture the chaos and excitement of a bustling street market in a foreign land, if you don't mind.",
        "Could you please paint a portrait of a wise old wizard with a long, flowing beard and a staff?",
        "I'd be thrilled if you could sketch a scene of a cozy, candlelit library filled with ancient books.",
        "Would you consider illustrating a fantastical underwater world with mermaids and seahorses?",
        "Create a surreal dreamscape where gravity doesn't exist, and objects float. Would you do that for me?",
        "Draw a fierce dragon guarding a treasure hoard deep within a cave, if it's not too much trouble.",
        "Imagine a medieval castle perched on a cliff, shrouded in mist. Could you bring this scene to life?",
        "Could you capture the beauty of a cherry blossom tree in full bloom, with petals gently falling in the wind?",
        "I'd appreciate your artistry in illustrating a bustling Parisian café scene with people sipping coffee and chatting.",
        "Would you mind drawing a peaceful, starry night in the desert with a solitary camel resting under the sky?",
        "Imagine a steampunk world where mechanical animals roam a Victorian-era city. Could you sketch it?",
        "Create a whimsical carnival with colorful tents, ferris wheels, and circus performers. I'd love to see it!",
        "Could you please paint a portrait of an elegant ballerina gracefully dancing on a moonlit stage?",
        "I'd be thrilled if you could sketch a majestic mountain range with a snow-capped peak touching the clouds.",
        "Would you consider illustrating a futuristic space colony on a distant planet, complete with advanced technology?",
        "Imagine a cozy cottage in the woods, surrounded by a lush forest. Could you bring this scene to life?",
        "Capture the beauty of a serene beach at sunrise, with gentle waves and seagulls in the distance.",
        "Could you create a scene of a bustling Asian street market filled with vibrant colors and exotic fruits?",
        "I'd appreciate your artistry in depicting a mystical forest where fireflies light up the night. Would you?",
        "Would you mind drawing a vibrant underwater coral reef teeming with colorful fish and marine life?",
        "Imagine an enchanted garden with talking flowers and whimsical creatures. Could you illustrate it?",
        "Paint a mythical phoenix rising from the ashes in a burst of flames and feathers. Would you do that?",
        "I'd love to see your drawing of a futuristic city skyline with towering skyscrapers and flying cars.",
        "Could you please sketch a scene of a peaceful countryside cottage with a winding path and a blooming garden?",
        "Capture the essence of a bustling New York City Times Square at night. It's such a dynamic scene!",
        "Imagine a post-apocalyptic wasteland reclaimed by nature and wildlife. Could you illustrate it?",
        "I'd appreciate it if you could create a whimsical tea party with talking animals in a storybook setting.",
        "I'd love to see your illustration of a medieval knight in shining armor on horseback, ready for battle.",
        "Could you please draw a serene beach scene with palm trees, crystal-clear water, and a hammock?",
        "Paint a dramatic thunderstorm over a Gothic castle on a moonlit night, if you're willing.",
        "I'd be thrilled if you could sketch a futuristic space station with astronauts floating in zero gravity.",
        "Would you consider illustrating a magical winter wonderland with snow-covered trees and a cozy cabin?",
        "Imagine a surreal forest where trees have eyes and whisper secrets. Could you bring it to life?",
        "Create an abstract representation of the concept of time. How would you visualize it?",
        "I'd appreciate your artistry in depicting a busy and crowded New York street.",
        "Could you please paint a breathtaking waterfall in a lush, tropical rainforest?",
        "I'd love to see your drawing of a grand, ornate cathedral with intricate stained glass windows.",
        "Imagine a serene garden with a koi pond and a graceful bridge. Could you illustrate it?",
        "Capture the beauty of a quaint European village nestled among rolling hills and vineyards.",
        "Could you create a surreal dreamscape of floating islands in the sky, each with its own unique landscape?",
        "I'd be thrilled if you could sketch a majestic dragon soaring through the clouds with wings outstretched.",
        "Would you consider illustrating a mythical forest inhabited by fantastical creatures like unicorns and griffins?",
        "Imagine a bustling harbor with ships from different eras docked alongside each other. Could you bring it to life?",
        "Paint a vibrant market square in Marrakech, Morocco, with colorful rugs, spices, and street performers.",
        "I'd appreciate your artistry in depicting a serene Japanese garden with a traditional tea house.",
        "Could you please draw a cozy, snow-covered cabin in the woods, smoke rising from the chimney?",
        "I'd love to see your illustration of a futuristic city on the ocean, complete with floating buildings and boats.",
        "A rendering of a magical forest where trees are made of crystal and emit a soft, enchanting glow.",
        "A scene of a romantic gondola ride through the canals of Venice under a starry sky. Would you?",
        "Capture the essence of a lively jazz club with musicians and dancers in a smoky, dimly lit room.",
        "Could you please paint a mythical underwater city with merfolk and seahorses, hidden beneath the waves?",
        "I'd be thrilled if you could sketch an ancient Egyptian pyramid rising from the desert sands.",
        "Would you consider illustrating a futuristic space colony on a distant planet with advanced technology?",
        "Imagine a serene countryside covered in a blanket of blooming cherry blossoms. Could you bring it to life?",
        "Paint a scene of a tranquil lakeside cabin at dawn, with mist rising from the water and birds in the distance.",
        "I'd appreciate your artistry in depicting a bustling medieval marketplace with merchants and jesters.",
        "Could you create a surreal dreamscape of a city skyline reflected in a giant puddle, merging reality and illusion?",
        "I'd love to see your drawing of a mystical forest illuminated by a radiant, full moon.",
        "Imagine an underwater world where ancient ruins are now home to an array of marine life. Could you illustrate it?",
        "Capture the beauty of a serene mountain lake surrounded by towering peaks and evergreen forests.",
        "Could you please sketch a vibrant carnival with colorful rides, cotton candy, and laughter in the air?",
        "I'd be thrilled if you could paint a majestic eagle soaring through a vivid sunset sky.",
        "Would you consider illustrating a magical garden with oversized flowers and whimsical insects?",
        "A futuristic cityscape with holographic billboards and a bustling hovercraft transportation system.",
        "Create a scene of a serene countryside cottage with a thatched roof, nestled among rolling hills and wildflowers.",
        "Capture the essence of a bustling Tokyo street with neon signs, sushi stalls, and crowds of people.",
        "Could you please paint an ancient forest where massive, ancient trees touch the sky?",
        "I'd appreciate your artistry in depicting a tranquil beach at twilight, with a bonfire and friends gathered around.",
        "I'd love to see your drawing of a bustling, steampunk-inspired metropolis with airships and gears everywhere.",
        "Imagine a mysterious, misty graveyard at midnight with old, weathered tombstones. Could you illustrate it?",
        "Paint a scene of a traditional Japanese tea ceremony with all its intricate rituals and serene atmosphere.",
        "Capture the beauty of a serene desert oasis with palm trees, a shimmering pool, and desert wildlife.",
        "Could you please sketch a mythical creature of your own invention, combining elements from different animals?",
        "I'd be thrilled if you could create a surreal dreamscape of a forest underwater, with fish swimming among the trees.",
        "Would you consider illustrating a vibrant Indian market with colorful textiles, spices, and street vendors?",
        "Imagine a magical realm where wizards duel with spells in a hidden library filled with ancient tomes. Could you bring it to life?",
        "I'd appreciate your artistry in depicting a tranquil garden with a cascading waterfall and vibrant flowers.",
        "Could you create a scene of a bustling medieval castle courtyard with knights, jesters, and a jousting tournament?",
        "Capture the essence of a lively street parade with colorful floats, marching bands, and confetti in the air.",
        "I'd love to see your drawing of a futuristic spaceport with sleek spacecraft and interstellar travelers.",
        "Imagine an enchanted forest where the trees have eyes and the animals hold secret meetings. Could you sketch it?",
        "Paint a scene of a cozy winter cabin with a roaring fireplace, warm blankets, and snow falling outside.",
        "Could you please illustrate a mythical phoenix rising from the ashes, surrounded by flames and glory?",
        "I'd be thrilled if you could create a surreal dreamscape of a cityscape within a soap bubble, floating in the sky.",
        "Would you consider depicting a mythical underwater kingdom ruled by a majestic sea serpent?",
        "Imagine a vibrant Indian wedding with intricate henna designs, colorful saris, and joyful dancing. Could you bring it to life?",
        "Capture the beauty of a serene Japanese Zen garden with meticulously raked gravel and carefully placed stones.",
        "Could you please sketch a tranquil forest glade with dappled sunlight and a gentle stream running through it?",
        "I'd love to see your drawing of a futuristic cityscape on a distant planet, with alien architecture and technology.",
        "Create a scene of a mystical, moonlit desert with sand dunes that seem to stretch to infinity.",
        "Paint a scene of a traditional Chinese lantern festival with colorful lanterns illuminating the night sky.",
        "Could you please create a surreal dreamscape of a world where buildings are made of books, and characters leap from the pages?",
        "Capture the beauty of a serene garden at twilight, with fireflies dancing among the flowers and a crescent moon in the sky.",
        "Imagine a surreal dreamscape where floating islands in the sky are connected by colorful bridges, like a fantastical city in the clouds. Could you illustrate it?",
        "Paint a scene of a peaceful countryside cottage nestled among rolling hills and fields of sunflowers, with a warm, golden sunset in the background.",
        "Capture the essence of a bustling New Orleans street parade with jazz bands, colorful floats, and people dancing in the streets.",
    };

    public static string[] AskTitles = new string[]
    {
        "Tranquil Countryside Sunset",
        "Futuristic Cityscape",
        "Enchanted Forest",
        "Bizarre Alien Planet",
        "Bustling Street Market",
        "Wise Old Wizard",
        "Cozy Library",
        "Fantastical Underwater World",
        "Surreal Dreamscape",
        "Guardian Dragon",
        "Misty Cliff Castle",
        "Cherry Blossom Beauty",
        "Parisian Café Scene",
        "Desert Dawn",
        "Steampunk City",
        "Carnival",
        "Ballerina",
        "Mountain range",
        "Space colony",
        "Cottage",
        "Sunrise Beach",
        "Asian street market",
        "Mystical forest",
        "Underwater Coral Reef",
        "Mystical Garden",
        "Rising Phoenix",
        "Future City Skyline",
        "Countryside Cottage",
        "Times Square Night",
        "Post-Apocalyptic Reclamation",
        "Whimsical Tea Party",
        "Medieval Knight",
        "Serene Beach",
        "Thunderstorm Castle",
        "Futuristic Space Station",
        "Winter Wonderland",
        "Whispering Forest",
        "Abstract Concept of Time",
        "New York street",
        "Breathtaking Waterfall",
        "Ornate Cathedral",
        "Tranquil Garden",
        "European Village",
        "Floating Islands in the Sky",
        "Soaring Dragon",
        "Forest with unicorns and griffins",
        "Harbor Scene",
        "Marrakech Market Square",
        "Japanese Zen Garden",
        "Cabin in the Woods",
        "Space beach",
        "Crystal Forest",
        "Romantic Gondola Ride",
        "Lively Jazz Club",
        "Mythical Underwater City",
        "Ancient Pyramid",
        "Space Colony",
        "Cherry Blossom Bliss",
        "Lakeside Cabin at Dawn",
        "Medieval Marketplace",
        "Cityscape in a Bubble",
        "Mystical Moonlit Forest",
        "Underwater Ruins",
        "Mountain Lake Serenity",
        "Vibrant Carnival",
        "Soaring Eagle",
        "Mythical Garden",
        "Futuristic City",
        "Countryside Cottage",
        "Busy Tokyo Street",
        "Ancient Forest",
        "Trainquil Beach",
        "Steampunk City",
        "Misty Graveyard",
        "Japanese Tea Ceremony",
        "Desert Oasis",
        "Unique Mythical Creature",
        "Underwater forest",
        "Indian Market",
        "Dueling Wizards",
        "Garden With Waterfall",
        "Medieval Castle",
        "Street Parade",
        "Spaceport",
        "Enchanted Forest",
        "Cozy Winter Cabin",
        "Phoenix",
        "City in a Soap Bubble",
        "Underwater kingdom",
        "Indian Wedding",
        "Japanese Zen Garden",
        "Tranquil Forest",
        "Alien city",
        "Moonlit Desert",
        "Chinese Lantern Festival",
        "Buildings Made of Books",
        "Twilight Garden with Fireflies",
        "Floating islands",
        "Countryside Cottage",
        "New Orleans Street Parade",
    };

    public static string[] AskTags = new string[]
    {
        "Tranquil",
        "Futuristic",
        "Enchanted",
        "Alien",
        "Market",
        "Wizard",
        "Library",
        "Fantastical",
        "Surreal",
        "Dragon",
        "Castle",
        "Cherry_Blossom",
        "Cafe",
        "Desert",
        "Steampunk",
        "Carnival",
        "Ballerina",
        "Mountain",
        "Space",
        "Cottage",
        "Beach",
        "Market",
        "Forest",
        "underwater",
        "garden",
        "phoenix",
        "City",
        "Cottage",
        "Time_Square",
        "post_apocalyptic",
        "tea_party",
        "Knight",
        "Beach",
        "Castle",
        "Space_Station",
        "Winter",
        "Forest",
        "Abstract",
        "New_York",
        "Waterfall",
        "Cathedral",
        "Garden",
        "Village",
        "island",
        "Dragon",
        "Forest",
        "Harbor",
        "Market",
        "Zen",
        "Cabin",
        "Beach",
        "Forest",
        "Venetian",
        "Jazz",
        "Underwater",
        "Pyramid",
        "Space",
        "Cherry_Blossom",
        "Cabin",
        "Market",
        "City",
        "Forest",
        "Ruins",
        "Mountain",
        "Carnival",
        "Eagle",
        "Garden",
        "City",
        "Cottage",
        "Tokyo",
        "Forest",
        "Beach",
        "City",
        "Graveyard",
        "tea_ceremony",
        "desert",
        "Creature",
        "Forest",
        "Market",
        "Wizard",
        "Waterfall",
        "Castle",
        "Parade",
        "Spaceport",
        "Forest",
        "Cabin",
        "Phoenix",
        "City",
        "Underwater",
        "Wedding",
        "Zen",
        "Forest",
        "City",
        "Desert",
        "Festival",
        "Book",
        "Garden",
        "Sky",
        "Cottage",
        "Parade",
    };

    public static IEnumerable<AskCreate> AskCreates => AskTitles
        .Zip(AskBodies, (title, body) => (title, body))
        .Zip(AskTags, (titleBody, tag) => new AskCreate()
        {
            Title = titleBody.title,
            Body = titleBody.body,
            Tags = new Tag[] { new Tag(tag) }
        });
}