using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using MediatR;

namespace Inklio.Api.Application.Commands;

/// <summary>
/// An request body to create a new Delivery
/// </summary>
[DataContract]
public class DeliveryCreateCommand : IRequest<bool>
{
    /// <summary>
    /// Gets or sets the ID of the Ask
    /// </summary>
    [IgnoreDataMember]
    [JsonIgnore]
    public int AskId { get; set; }

    /// <summary>
    /// Gets or sets the Body of the Delivery.
    /// </summary>
    [DataMember(Name = "body")]
    [JsonPropertyName("body")]
    [MaxLength(1600000)]
    public string Body { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets a flag indicating whether to include the parent tags when creating the delivery.
    /// </summary>
    [DataMember(Name = "includeAskTags")]
    [JsonPropertyName("includeAskTags")]
    public bool IncludeAskTags { get; set; } = true;

    /// <summary>
    /// Gets or set the tags associated with the Delivery
    /// </summary>
    [JsonIgnore]
    public IEnumerable<IFormFile>? Images { get; set; } = null;

    /// <summary>
    /// Gets or sets a flag indicating whether or not the delivery generated by AI.
    /// </summary>
    [DataMember(Name = "isAi")]
    [JsonPropertyName("isAi")]
    public bool IsAi { get; set; }

    /// <summary>
    /// Gets or sets a flag indicating whether or not the delivery NSFL.
    /// </summary>
    [DataMember(Name = "isNsfl")]
    [JsonPropertyName("isNsfl")]
    public bool IsNsfl { get; set; }

    /// <summary>
    /// Gets or sets a flag indicating whether or not the delivery is NSFW.
    /// </summary>
    [DataMember(Name = "isNsfw")]
    [JsonPropertyName("isNsfw")]
    public bool IsNsfw { get; set; }

    /// <summary>
    /// Gets or sets a flag indicating whether or not the delivery contains a spoiler.
    /// </summary>
    [DataMember(Name = "isSpoiler")]
    [JsonPropertyName("isSpoiler")]
    public bool IsSpoiler { get; set; }

    /// <summary>
    /// Gets or sets the Title of the Delivery.
    /// </summary>
    [DataMember(Name = "title")]
    [JsonPropertyName("title")]
    [MaxLength(200)]
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Gets or set the tags associated with the Delivery
    /// </summary>
    [DataMember(Name = "tags")]
    [JsonPropertyName("tags")]
    public IEnumerable<Tag> Tags { get; set; } = new Tag[] { };

    /// <summary>
    /// Gets or sets the ID of the user
    /// </summary>
    [IgnoreDataMember]
    [JsonIgnore]
    public UserId UserId { get; set; }
}